Algoritmo "Exercicio 7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Ribeiro
// Data atual  : 07/10/2022
Var
   // Seção de Declarações das variáveis
   contador,contadora, fatorial:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

Fimalgoritmo